# Generated by Django 5.2.4 on 2025-07-09 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('management', '0003_alter_student_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='management.teacher'),
        ),
    ]
