# Generated by Django 5.2.4 on 2025-07-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='classTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='classroom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
