# Generated by Django 5.2.4 on 2025-07-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todoTitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
